[project]
name = "lemma"
version = "0.0.1"
requires-python = ">=3.9"
dynamic = ["dependencies"]

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "wheel", "Cython"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}